### ISSUE TITLE
non ascii char

### ISSUE THREAD

**Issue by TerraRoot** [elmerilaakkonen/squish-velocity#1]
hi, ran this on debian oldstable, python3, but it failed with:
File "squish_velocity.py", line 34
SyntaxError: Non-ASCII character '\xc2' in file squish_velocity.py on line 34, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

I removed the degree symbol's from the .py and it worked great.

**Comment by elmerilaakkonen** [comment]
Thanks, updated the .py!
